apiVersion: 1
datasources:
 - name: Loki
   type: loki
   access: proxy
   orgId: 1
   uid: 4
   url: http://carrier-loki:3100
   password:
   user:
   database:
   basicAuth: false
   isDefault: false
   jsonData: {"keepCookies":[]}
   version: 1
   editable: true
